In [9]:
import numpy as np
def proba_to_label_np(probas):
    predict_levels = probas > 0.5
    predicted_labels = np.sum(predict_levels, axis=1)
    return predicted_labels

def corn_label_from_logits_np(logits):
    #probas = torch.sigmoid(logits)
    probas = 1/(1 + np.exp(-logits))
    probas = np.cumprod(probas, axis=1)
    predict_levels = probas > 0.5
    predicted_labels = np.sum(predict_levels, axis=1)
    return predicted_labels

In [8]:
proba_to_label_np(np.asarray([[0.0, 0.0]]))

array([0])

In [3]:
probas = np.asarray([[0.934, 0.861, 0.323, 0.492, 0.295],
                        [0.496, 0.485, 0.267, 0.124, 0.058],
                        [0.985, 0.967, 0.920, 0.819, 0.506]])

In [53]:
logits = np.asarray([[14.152, -6.1942, 0.47710, 0.96850],
                        [65.667, 0.303, 11.500, -4.524],
                        [0.0, 0.5, 0.5, 0.5]])
corn_label_from_logits_np(logits)

array([1, 3, 0])

In [60]:
logits[:, [2,0,3]]

array([[ 0.4771, 14.152 ,  0.9685],
       [11.5   , 65.667 , -4.524 ],
       [ 0.5   ,  0.    ,  0.5   ]])

In [57]:
preds = corn_label_from_logits_np(logits)
probas = 1/(1 + np.exp(-logits))
probas = np.cumprod(probas, axis=1)
soft_labels = 0.5 - (probas * np.eye(probas.shape[1])[preds-1]).sum(axis=1)
soft_labels = preds + soft_labels
soft_labels

array([0.50000071, 2.9248301 , 0.37941232])

In [47]:
np.eye(probas.shape[1])[preds-1]

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [42]:
preds

array([1, 3])

In [45]:
np.eye(probas.shape[1])[preds-1]

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
probas.select

AttributeError: 'numpy.ndarray' object has no attribute 'select'

In [34]:
preds-1

array([0, 2])

In [32]:
probas

array([[9.99999286e-01, 2.03707593e-03, 1.25700387e-03, 9.11102069e-04],
       [1.00000000e+00, 5.75175727e-01, 5.75169901e-01, 6.17110746e-03]])

In [25]:
probas

array([[9.99999286e-01, 2.03707593e-03, 1.25700387e-03, 9.11102069e-04],
       [1.00000000e+00, 5.75175727e-01, 5.75169901e-01, 6.17110746e-03]])